M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu21.10.1} date Tue 19 Apr 2022 01:51:08 AM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-19T01:51:08-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu21.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T2
X4.6417Y-4.5945
T1
G00X4.4685Y-4.6043
M15
G01X4.4685Y-4.5846
M16
G05
T0
M30
